#!/bin/bash

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 01 02 03 04 05 06 07 08 09 00

auto-git-pull &
bspwm-conf-xrandr
sct 4500
bspwm-conf-desktops

bspc config border_width 2
bspc config window_gap 4
bspc config top_padding 23

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config pointer_motion_interval 2
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config external_rules_command "$HOME/.local/bin/bspwm-external-rules"

bspc config normal_border_color "#3A3F4B"
bspc config active_border_color "#0366d6"
bspc config focused_border_color "#005f5f"
bspc config presel_feedback_color "#d70000"

# bspc rules
bspc rule -a Nextcloud --one-shot hidden=on
bspc rule -a qBittorrent --one-shot hidden=on

# launch app
pgrep -x sxhkd >/dev/null || sxhkd &
pgrep -x polybar >/dev/null || polybar-run &
pgrep -x greenclip >/dev/null || greenclip daemon &
picom --config ~/.config/picom/picom.conf &
# pgrep -x mpd >/dev/null || mpd &
pgrep -x blueman-applet >/dev/null || blueman-applet &
libinput-gestures-setup start &
nm-applet &
warpd &
kwalletd5 &
mullvad-vpn &
telegram-desktop &
nextcloud &
qbittorrent &
# superproductivity &
# pgrep -x spotify >/dev/null || sleep 3 && firejail spotify --private &
# pgrep -x firefox >/dev/null || firefox &

xset r rate 350 62 &
numlockx on &
xsetroot -cursor_name left_ptr &
feh --bg-fill ~/pictures/wallpapers/wallpaper &

tdrop -am -h 1% -w 1% merkuro-calendar
tdrop -am merkuro-calendar
tdrop -am -n 1 -h 90% -w 70% -y 25 -x 15% alacritty -e btop
tdrop -am -n 1 alacritty -e btop
