#!/bin/bash

# Что делает этот скрипт:
# - Позволяет быстро запускать mdbook-базы на гитлабе (и прочие юрлки и команды)

# data - переменная хранит названия программ и папки для открытия

# стуркура bases.json

# [
#   {
#     "name": "База знаний",
#     "commands": [
#       {
#         "app": "firefox",
#         "arguments": "--new-window https://inauris.gitlab.io/base-of-knowledges/"
#       }
#     ]
#   },
#   {
#     "name": "Roadmap",
#     "commands": [
#       {
#         "app": "firefox",
#         "arguments": "--new-window https://inauris.gitlab.io/roadmap/"
#       }
#     ]
#   }
# ]

xkb-switch -s us &

rofi_command='rofi -m -1 -theme themes/mdbooks.rasi'

data="/home/inauris/.config/rofi/data/mdbooks.json"

# Variable passed to rofi
options="$(jq -r '.[].name' "$data")"

chosen="$(echo -e "$options" | $rofi_command -p "mdBooks" -dmenu)"

[[ -z "$chosen" ]] && exit 1

commands=$(jq -r ".[] | select(.name==\"$chosen\") .request" "$data")

for row in $(echo "${commands}" | jq -r '.[] | @base64'); do
    command=$(echo "${row}" | base64 --decode | jq -r ".app")
    command+=" "
    command+=$(echo "${row}" | base64 --decode | jq -r ".arguments")

    $command
done
